# Generated by Django 3.1.7 on 2021-04-13 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(unique=True)),
                ('course_name', models.CharField(max_length=20)),
                ('grade_level', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equalearn.user')),
                ('referred_organization', models.CharField(max_length=60)),
                ('proof_of_low_income', models.BooleanField()),
            ],
            bases=('equalearn.user',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equalearn.user')),
                ('preference_online', models.BooleanField()),
                ('date_started', models.DateField(auto_now_add=True)),
            ],
            bases=('equalearn.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('school', models.CharField(max_length=50)),
                ('user_id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='equalearn.client')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='equalearn.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='equalearn.subject')),
                ('user_id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='equalearn.client')),
                ('user_id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='equalearn.tutor')),
            ],
        ),
    ]
