# Generated by Django 3.1.7 on 2021-04-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equalearn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='subject',
            new_name='subject_id',
        ),
    ]
