# Generated by Django 3.2 on 2021-04-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equalearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='current_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='equalearn.tutor'),
        ),
        migrations.CreateModel(
            name='schedule_student',
            fields=[
                ('student_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='equalearn.student')),
            ],
        ),
    ]
