# Generated by Django 3.2 on 2021-04-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equalearn', '0002_auto_20210415_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equalearn.user')),
                ('position', models.CharField(max_length=50)),
            ],
            bases=('equalearn.user',),
        ),
        migrations.AlterField(
            model_name='schedule_student',
            name='weekday',
            field=models.CharField(choices=[('Monday', 0), ('Tuesday', 1), ('Wednesday', 2), ('Thursday', 3), ('Friday', 4), ('Saturday', 5), ('Sunday', 6)], max_length=15),
        ),
        migrations.CreateModel(
            name='PendingSession',
            fields=[
                ('sessions_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('weekday', models.CharField(max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('takes_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendingsessions', to='equalearn.takes')),
                ('user_id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendingsessions', to='equalearn.client')),
                ('user_id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendingsessions', to='equalearn.tutor')),
            ],
        ),
    ]
