# Generated by Django 3.1.7 on 2021-04-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equalearn', '0004_auto_20210415_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='preference_online',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
